// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * Mock Verifier for Testing
 * In production, use Verifier.sol generated by snarkjs
 */
contract MockVerifier {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata input
    ) external pure returns (bool) {
        // Always returns true for testing
        // In production, verify the actual Groth16 proof
        return true;
    }
}
