/**
 * Deployment Script for Private Voting System
 * Deploy contracts to Paseo Asset Hub testnet
 */

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log("🚀 Deploying Private Voting System...\n");

    const [deployer] = await ethers.getSigners();
    console.log(`📍 Deploying from: ${deployer.address}`);

    // Get keyholder addresses from environment
    const keyholder0 = process.env.KEYHOLDER_0;
    const keyholder1 = process.env.KEYHOLDER_1;
    const keyholder2 = process.env.KEYHOLDER_2;

    if (!keyholder0 || !keyholder1 || !keyholder2) {
        throw new Error("Missing keyholder addresses in environment variables");
    }

    const deployments = {};

    // Step 1: Deploy ChaumPedersen
    console.log("\n1️⃣  Deploying ChaumPedersen...");
    const ChaumPedersen = await ethers.getContractFactory("ChaumPedersen");
    const chaumPedersen = await ChaumPedersen.deploy();
    await chaumPedersen.deployed();
    deployments.chaumPedersen = chaumPedersen.address;
    console.log(`   ✅ ChaumPedersen deployed: ${chaumPedersen.address}`);

    // Step 2: Deploy Verifier (this would be generated by snarkjs)
    // For now, we'll create a mock verifier
    console.log("\n2️⃣  Deploying Verifier...");
    
    // In production, you would use the verifier generated by snarkjs:
    // snarkjs groth16 setup circuit.r1cs pot12_final.ptau circuit_0000.zkey
    // snarkjs zkey contribute circuit_0000.zkey circuit_final.zkey
    // snarkjs zkey export solidityverifier circuit_final.zkey Verifier.sol
    
    // For now, deploying a mock verifier
    const MockVerifier = await ethers.getContractFactory("MockVerifier");
    const verifier = await MockVerifier.deploy();
    await verifier.deployed();
    deployments.verifier = verifier.address;
    console.log(`   ✅ Verifier (Mock) deployed: ${verifier.address}`);

    // Step 3: Deploy PrivateVoting
    console.log("\n3️⃣  Deploying PrivateVoting...");
    const PrivateVoting = await ethers.getContractFactory("PrivateVoting");
    const privateVoting = await PrivateVoting.deploy(
        keyholder0,
        keyholder1,
        keyholder2,
        verifier.address,
        chaumPedersen.address
    );
    await privateVoting.deployed();
    deployments.privateVoting = privateVoting.address;
    console.log(`   ✅ PrivateVoting deployed: ${privateVoting.address}`);

    // Save deployments
    const deploymentsPath = path.join(__dirname, "..", "deployments.json");
    fs.writeFileSync(deploymentsPath, JSON.stringify(deployments, null, 2));

    console.log("\n✨ Deployment Complete!\n");
    console.log("📋 Addresses saved to deployments.json:");
    Object.entries(deployments).forEach(([name, address]) => {
        console.log(`   ${name}: ${address}`);
    });

    // Create .env file if it doesn't exist
    const envPath = path.join(__dirname, "..", ".env");
    if (!fs.existsSync(envPath)) {
        const envContent = `REACT_APP_CONTRACT_ADDRESS=${privateVoting.address}
REACT_APP_RPC_URL=wss://asset-hub-paseo-rpc.polkadot.io
REACT_APP_CHAIN_ID=420420421

KEYHOLDER_0=${keyholder0}
KEYHOLDER_1=${keyholder1}
KEYHOLDER_2=${keyholder2}`;

        fs.writeFileSync(envPath, envContent);
        console.log("\n📝 Created .env file with deployment addresses");
    }

    console.log("\n🎉 Ready to use! Update your .env file with these addresses.");
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
