require("dotenv").config();
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * Deployment script for Polkadot Private Voting System
 * Deploys contracts in order:
 * 1. ChaumPedersen.sol
 * 2. Verifier.sol (generated by snarkjs)
 * 3. PrivateVoting.sol
 */

async function main() {
    console.log("=================================================");
    console.log("Deploying Private Voting System");
    console.log("=================================================\n");

    const [deployer] = await ethers.getSigners();
    console.log(`Deploying contracts with account: ${deployer.address}\n`);

    // Get keyholder addresses from environment
    const keyholder0 = process.env.KEYHOLDER_0;
    const keyholder1 = process.env.KEYHOLDER_1;
    const keyholder2 = process.env.KEYHOLDER_2;

    if (!keyholder0 || !keyholder1 || !keyholder2) {
        throw new Error("Missing keyholder addresses in .env file");
    }

    console.log("Keyholders:");
    console.log(`  0: ${keyholder0}`);
    console.log(`  1: ${keyholder1}`);
    console.log(`  2: ${keyholder2}\n`);

    // Deploy ChaumPedersen
    console.log("1. Deploying ChaumPedersen...");
    const ChaumPedersen = await hre.ethers.getContractFactory("ChaumPedersen");
    const chaumPedersen = await ChaumPedersen.deploy();
    await chaumPedersen.waitForDeployment();
    const chaumPedersenAddress = await chaumPedersen.getAddress();
    console.log(`   ChaumPedersen deployed to: ${chaumPedersenAddress}\n`);

    // Deploy Verifier (This should be generated by snarkjs)
    console.log("2. Deploying Verifier...");
    let verifierAddress;
    try {
        const Verifier = await hre.ethers.getContractFactory("Verifier");
        const verifier = await Verifier.deploy();
        await verifier.waitForDeployment();
        verifierAddress = await verifier.getAddress();
        console.log(`   Verifier deployed to: ${verifierAddress}\n`);
    } catch (error) {
        console.log("   Note: Verifier.sol not found.");
        console.log("   Generate it with: snarkjs groth16 setup circuit.r1cs pot12_final.ptau...");
        console.log("   For now, using ChaumPedersen address as placeholder.\n");
        verifierAddress = chaumPedersenAddress;
    }

    // Deploy PrivateVoting
    console.log("3. Deploying PrivateVoting...");
    const PrivateVoting = await hre.ethers.getContractFactory("PrivateVoting");
    const privateVoting = await PrivateVoting.deploy(
        keyholder0,
        keyholder1,
        keyholder2,
        verifierAddress,
        chaumPedersenAddress
    );
    await privateVoting.waitForDeployment();
    const privateVotingAddress = await privateVoting.getAddress();
    console.log(`   PrivateVoting deployed to: ${privateVotingAddress}\n`);

    // Save deployment addresses
    const deployments = {
        network: hre.network.name,
        deployer: deployer.address,
        timestamp: new Date().toISOString(),
        contracts: {
            ChaumPedersen: chaumPedersenAddress,
            Verifier: verifierAddress,
            PrivateVoting: privateVotingAddress
        },
        keyholders: {
            0: keyholder0,
            1: keyholder1,
            2: keyholder2
        }
    };

    const deploymentPath = path.join(__dirname, "../deployments.json");
    fs.writeFileSync(deploymentPath, JSON.stringify(deployments, null, 2));

    console.log("=================================================");
    console.log("Deployment Summary");
    console.log("=================================================");
    console.log(`Network: ${hre.network.name}`);
    console.log(`Deployer: ${deployer.address}\n`);
    console.log("Deployed Contracts:");
    console.log(`  ChaumPedersen: ${chaumPedersenAddress}`);
    console.log(`  Verifier: ${verifierAddress}`);
    console.log(`  PrivateVoting: ${privateVotingAddress}\n`);
    console.log(`Deployment addresses saved to: ${deploymentPath}`);
    console.log("=================================================\n");

    // Print environment variable template
    console.log("Update your .env file with:");
    console.log(`REACT_APP_CONTRACT_ADDRESS=${privateVotingAddress}`);
    console.log(`REACT_APP_VERIFIER_ADDRESS=${verifierAddress}`);
    console.log(`REACT_APP_CHAUM_PEDERSEN_ADDRESS=${chaumPedersenAddress}`);
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
